// <auto-generated />
namespace bluesky.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitAuth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitAuth));
        
        string IMigrationMetadata.Id
        {
            get { return "202511072006444_InitAuth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
