//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bluesky.Auth
{
    public partial class CrearSesion
    {
        protected global::System.Web.UI.WebControls.Content HeadAuthRegister;
        protected global::System.Web.UI.WebControls.Content MainAuthRegister;
    }
}
