//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bluesky.Auth
{
    public partial class IniciarSesion
    {
        protected global::System.Web.UI.WebControls.Content HeadAuthLogin;
        protected global::System.Web.UI.WebControls.Content MainAuthLogin;
    }
}
