//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bluesky.Auth
{
    public partial class OlvidasteContrasena
    {
        protected global::System.Web.UI.WebControls.Content HeadAuthForgot;
        protected global::System.Web.UI.WebControls.Content MainAuthForgot;
    }
}
